# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/webcretaire/Code/ExifStat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/webcretaire/Code/ExifStat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/webcretaire/Code/ExifStat/CMakeFiles /home/webcretaire/Code/ExifStat/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/webcretaire/Code/ExifStat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ExifStat

# Build rule for target.
ExifStat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExifStat
.PHONY : ExifStat

# fast build rule for target.
ExifStat/fast:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/build
.PHONY : ExifStat/fast

cpp_exiftool/src/ExifTool.o: cpp_exiftool/src/ExifTool.cpp.o

.PHONY : cpp_exiftool/src/ExifTool.o

# target to build an object file
cpp_exiftool/src/ExifTool.cpp.o:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/ExifTool.cpp.o
.PHONY : cpp_exiftool/src/ExifTool.cpp.o

cpp_exiftool/src/ExifTool.i: cpp_exiftool/src/ExifTool.cpp.i

.PHONY : cpp_exiftool/src/ExifTool.i

# target to preprocess a source file
cpp_exiftool/src/ExifTool.cpp.i:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/ExifTool.cpp.i
.PHONY : cpp_exiftool/src/ExifTool.cpp.i

cpp_exiftool/src/ExifTool.s: cpp_exiftool/src/ExifTool.cpp.s

.PHONY : cpp_exiftool/src/ExifTool.s

# target to generate assembly for a file
cpp_exiftool/src/ExifTool.cpp.s:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/ExifTool.cpp.s
.PHONY : cpp_exiftool/src/ExifTool.cpp.s

cpp_exiftool/src/ExifToolPipe.o: cpp_exiftool/src/ExifToolPipe.cpp.o

.PHONY : cpp_exiftool/src/ExifToolPipe.o

# target to build an object file
cpp_exiftool/src/ExifToolPipe.cpp.o:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/ExifToolPipe.cpp.o
.PHONY : cpp_exiftool/src/ExifToolPipe.cpp.o

cpp_exiftool/src/ExifToolPipe.i: cpp_exiftool/src/ExifToolPipe.cpp.i

.PHONY : cpp_exiftool/src/ExifToolPipe.i

# target to preprocess a source file
cpp_exiftool/src/ExifToolPipe.cpp.i:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/ExifToolPipe.cpp.i
.PHONY : cpp_exiftool/src/ExifToolPipe.cpp.i

cpp_exiftool/src/ExifToolPipe.s: cpp_exiftool/src/ExifToolPipe.cpp.s

.PHONY : cpp_exiftool/src/ExifToolPipe.s

# target to generate assembly for a file
cpp_exiftool/src/ExifToolPipe.cpp.s:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/ExifToolPipe.cpp.s
.PHONY : cpp_exiftool/src/ExifToolPipe.cpp.s

cpp_exiftool/src/TagInfo.o: cpp_exiftool/src/TagInfo.cpp.o

.PHONY : cpp_exiftool/src/TagInfo.o

# target to build an object file
cpp_exiftool/src/TagInfo.cpp.o:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/TagInfo.cpp.o
.PHONY : cpp_exiftool/src/TagInfo.cpp.o

cpp_exiftool/src/TagInfo.i: cpp_exiftool/src/TagInfo.cpp.i

.PHONY : cpp_exiftool/src/TagInfo.i

# target to preprocess a source file
cpp_exiftool/src/TagInfo.cpp.i:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/TagInfo.cpp.i
.PHONY : cpp_exiftool/src/TagInfo.cpp.i

cpp_exiftool/src/TagInfo.s: cpp_exiftool/src/TagInfo.cpp.s

.PHONY : cpp_exiftool/src/TagInfo.s

# target to generate assembly for a file
cpp_exiftool/src/TagInfo.cpp.s:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/cpp_exiftool/src/TagInfo.cpp.s
.PHONY : cpp_exiftool/src/TagInfo.cpp.s

src/FileManager.o: src/FileManager.cpp.o

.PHONY : src/FileManager.o

# target to build an object file
src/FileManager.cpp.o:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/src/FileManager.cpp.o
.PHONY : src/FileManager.cpp.o

src/FileManager.i: src/FileManager.cpp.i

.PHONY : src/FileManager.i

# target to preprocess a source file
src/FileManager.cpp.i:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/src/FileManager.cpp.i
.PHONY : src/FileManager.cpp.i

src/FileManager.s: src/FileManager.cpp.s

.PHONY : src/FileManager.s

# target to generate assembly for a file
src/FileManager.cpp.s:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/src/FileManager.cpp.s
.PHONY : src/FileManager.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ExifStat.dir/build.make CMakeFiles/ExifStat.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ExifStat"
	@echo "... edit_cache"
	@echo "... cpp_exiftool/src/ExifTool.o"
	@echo "... cpp_exiftool/src/ExifTool.i"
	@echo "... cpp_exiftool/src/ExifTool.s"
	@echo "... cpp_exiftool/src/ExifToolPipe.o"
	@echo "... cpp_exiftool/src/ExifToolPipe.i"
	@echo "... cpp_exiftool/src/ExifToolPipe.s"
	@echo "... cpp_exiftool/src/TagInfo.o"
	@echo "... cpp_exiftool/src/TagInfo.i"
	@echo "... cpp_exiftool/src/TagInfo.s"
	@echo "... src/FileManager.o"
	@echo "... src/FileManager.i"
	@echo "... src/FileManager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

